services:
  app:
    build: .
    ports:
    - "8081:8081"
    container_name: pos-be
    depends_on:
      db:
        condition: service_healthy

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kiotdb
      - SPRING_DATASOURCE_USERNAME=kiot
      - SPRING_DATASOURCE_PASSWORD=kiot123
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./upload:/app/upload
    networks:
      - kiot-network

  db:
    container_name: pos-db
    image: mysql:lts
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=kiotdb
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=kiot
      - MYSQL_PASSWORD=kiot123
    volumes:
      - mysql-data:/var/lib/mysql
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - kiot-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  kiot-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local 